# Generated by Django 3.2.7 on 2021-12-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_accessrecord_topic_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='desc',
        ),
    ]
