# Generated by Django 3.2.7 on 2021-12-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_customer_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contect',
            name='desc',
        ),
    ]
